[channel]
generator = utipod
xmlbase = http://174.89.235.81:8080/UCATGf8vE2nWDdnEtBtfcsZw
title = "Jedaal"
link = https://www.youtube.com/channel/UCATGf8vE2nWDdnEtBtfcsZw
description = "This is the official Youtube channel of Jedaal TV, .\n\nCopyright © 2022 by Ali Alizadeh\nAll rights reserved. This channel's contents or any portion thereof may not be reproduced or used in any manner whatsoever without the express written permission of the content owner.\nDMCA - § 512(f) Misrepresentations Section 512(f) deters false claims of infringement by imposing liability on anyone who makes such claims, for the damages suffered by other parties as a result of the OSP's reliance on the false claim, and for associated legal fees.\n\nکانال رسمی تلویزیون اینترنتی جدال\nتمام حقوق این کانال متعلق به  علی علیزاده میباشد\n\nجدال اولین رسانه تماما مستقل و مشترک-محور زبان فارسی است. اگر خارج  از ایران زندگی میکنید با پرداخت  قیمت یک قهوه در ماه  و اگر  داخل  ایران با پرداخت داوطلبانه مبلغ حداقل   ۲۰هزار تومن جدال را تداوم  ببخشید\n\nاشتراک برای ایرانیان خارج کشور \npatreon.com/jedaal\n\nحمایت در پی‌پل\nhttps://www.paypal.com/paypalme/jedaal\n\n برای داخل کشور\nبانک ملی بنام مجید علیزاده\n6037991815099597\n"

[channel "image"]
url = https://yt3.ggpht.com/ytc/AKedOLRvUGpGU-37xYAdhLUaErIJQILyHhweJBkpMM65rw=s0

