[item]
guid = anqMFN09yec
title = "چرا ایران چین نشد؟ مقایسه تطبیقی سرمایه‌داری در ایران و چین در گفتگو با پروفسور محسن مسرت"
description = ""
author = Jedaal
source = https://www.youtube.com/channel/UCATGf8vE2nWDdnEtBtfcsZw
link = https://www.youtube.com/watch?v=anqMFN09yec
category = "News & Politics"
pubdate = Mon, 18 Jul 2022 00:00:00 -0000
enclosure = anqMFN09yec.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/anqMFN09yec/maxresdefault.jpg

