[item]
guid = Etxmlmk-atc
title = "درباره کریدور شمال جنوب چه میدانید؟"
description = "این کریدور چه تاثیری بر سفره مردم ایران دارد؟ ایا میشود به جای فروش نفت از ترانزیت پول درآورد؟ آیا توسعه ترانزیت ایران را کشوری توسعه‌یافته‌تر میکند؟\n.\nبخش‌هایی از جدال سوم تیر با احمد صالحی"
author = Jedaal
source = https://www.youtube.com/channel/UCATGf8vE2nWDdnEtBtfcsZw
link = https://www.youtube.com/watch?v=Etxmlmk-atc
category = "News & Politics"
pubdate = Sun, 17 Jul 2022 00:00:00 -0000
enclosure = Etxmlmk-atc.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/Etxmlmk-atc/sddefault.webp

